<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;

class CreateCartRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array|string>
     */
    public function rules(): array
    {
        return [
            'user_id'=>'required|exists:users,id',
            'product_id'=>'required|exists:products,id',
            'count'=>'required|numeric',
        ];
    }

    public function messages()
    {
        return [
            'user_id.*'=>'يرجى تحديد المستخدم',
        ]; // TODO: Change the autogenerated stub
    }

    protected function failedValidation(Validator $validator)
    {
        throw new HttpResponseException(response()->json(['msg'=>$validator->errors()->getMessageBag()]));
    }
}
